# site properties and page defaults
title: Health Informatics Lab
subtitle: at the USF School of Information
description: A collaboration of faculty, students, and partners to explore the intersection of health, information, and technology.
header: images/Background_2.jpeg
footer: images/Background_3.jpeg
proofer: false

# site social media and other links
links:
  email: contact@jimandrews@usf.edu
  orcid: 0000-0001-6795-9003
  google-scholar: https://scholar.google.com/citations?user=hded178AAAAJ&hl=en
  github: JimAndrewsFL
  twitter: JimAndrewsFL


### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
